name: Checkmarx SAST on PR

on:
  pull_request:
    types: [opened, reopened]   # only when PR is created or reopened
    branches: [ master ]

jobs:
  cx-sast:
    runs-on: ubuntu-latest

    env:
      CHECKMARX_BASE_URI: ${{ secrets.CHECKMARX_BASE_URI }}   # e.g. https://ast.checkmarx.net
      CHECKMARX_TENANT:   ${{ secrets.CHECKMARX_TENANT }}
      CHECKMARX_API_KEY:  ${{ secrets.CHECKMARX_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install prerequisites (jq)
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Install Checkmarx CLI (via GitHub Assets API)
        run: |
          set -euxo pipefail

          # First try: latest release asset id
          ASSET_ID="$(curl -s https://api.github.com/repos/Checkmarx/ast-cli/releases/latest \
            | jq -r '.assets[] | select(.name | test("linux_amd64\\.tar\\.gz$")) .id' | head -n1)"

          # Fallback: pinned version if latest isn't resolvable
          if [ -z "${ASSET_ID:-}" ] || [ "${ASSET_ID}" = "null" ]; then
            VER="2.3.36"
            ASSET_ID="$(curl -s https://api.github.com/repos/Checkmarx/ast-cli/releases/tags/${VER} \
              | jq -r '.assets[] | select(.name | test("linux_amd64\\.tar\\.gz$")) .id' | head -n1)"
          fi

          # Download actual tarball stream
          curl -L -H "Accept: application/octet-stream" \
            "https://api.github.com/repos/Checkmarx/ast-cli/releases/assets/${ASSET_ID}" \
            -o cx.tar.gz

          tar -xzf cx.tar.gz
          sudo mv cx /usr/local/bin/cx
          cx version

      - name: Configure Checkmarx
        run: |
          set -euxo pipefail
          cx configure set base_uri "$CHECKMARX_BASE_URI"
          cx configure set tenant "$CHECKMARX_TENANT"
          cx configure set api_key "$CHECKMARX_API_KEY"

      - name: Run SAST scan for this PR
        run: |
          set -euxo pipefail
          PROJECT="pr-${{ github.event.repository.name }}-${{ github.event.pull_request.number }}"
          BRANCH="${{ github.head_ref }}"
          cx scan create \
            --project-name "$PROJECT" \
            --branch "$BRANCH" \
            --sast \
            --async false

      - name: Summary
        if: always()
        run: |
          echo "### Checkmarx SAST triggered for PR #${{ github.event.pull_request.number }}" >> $GITHUB_STEP_SUMMARY
          echo "- Project: pr-${{ github.event.repository.name }}-${{ github.event.pull_request.number }}" >> $GITHUB_STEP_SUMMARY
          echo "- Branch:  ${{ github.head_ref }}" >> $GITHUB_STEP_SUMMARY
