name: Checkmarx PR Version Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master ]

jobs:
  cx-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Checkmarx CLI
        run: |
          set -euxo pipefail
          curl -L https://github.com/Checkmarx/ast-cli/releases/latest/download/ast-cli_linux_amd64.tar.gz -o cx.tar.gz
          tar -xzf cx.tar.gz
          sudo mv cx /usr/local/bin/cx

      - name: Display Checkmarx CLI version
        run: |
          echo "### ✅ Checkmarx CLI Version" >> $GITHUB_STEP_SUMMARY
          cx version >> $GITHUB_STEP_SUMMARY
