name: Checkmarx SAST on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master ]

jobs:
  cx-sast:
    runs-on: ubuntu-latest

    env:
      CHECKMARX_BASE_URI: ${{ secrets.CHECKMARX_BASE_URI }}
      CHECKMARX_TENANT:   ${{ secrets.CHECKMARX_TENANT }}    
      CHECKMARX_API_KEY:  ${{ secrets.CHECKMARX_API_KEY }}   

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Checkmarx CLI
        run: |
         set -euxo pipefail
         curl -L -o cx.tar.gz https://github.com/Checkmarx/ast-cli/releases/latest/download/ast-cli_linux_amd64.tar.gz
         tar -xzf cx.tar.gz
         sudo mv cx /usr/local/bin/cx

      - name: Configure Checkmarx
        run: |
          set -euxo pipefail
          cx configure set base_uri "$CHECKMARX_BASE_URI"
          cx configure set tenant "$CHECKMARX_TENANT"
          cx configure set api_key "$CHECKMARX_API_KEY"

      - name: Run SAST scan for this PR
        run: |
          set -euxo pipefail
          PROJECT="pr-${{ github.event.repository.name }}-${{ github.event.pull_request.number }}"
          BRANCH="${{ github.head_ref }}"
          cx scan create \
            --project-name "$PROJECT" \
            --branch "$BRANCH" \
            --sast \
            --async false

      - name: Summarize results
        if: always()
        run: |
          echo "### ✅ Checkmarx SAST triggered for PR #${{ github.event.pull_request.number }}" >> $GITHUB_STEP_SUMMARY
          echo "- Project: pr-${{ github.event.repository.name }}-${{ github.event.pull_request.number }}" >> $GITHUB_STEP_SUMMARY
          echo "- Branch:  ${{ github.head_ref }}" >> $GITHUB_STEP_SUMMARY
