name: Checkmarx CLI Install Test

on:
  pull_request:
    types: [opened, reopened]
    branches: [ master ]

jobs:
  cx-cli-test:
    runs-on: ubuntu-latest

    env:
      CHECKMARX_BASE_URI: ${{ secrets.CHECKMARX_BASE_URI }}
      CHECKMARX_TENANT:   ${{ secrets.CHECKMARX_TENANT }}
      CHECKMARX_API_KEY:  ${{ secrets.CHECKMARX_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq (for parsing)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Install Checkmarx CLI
        run: |
          set -euxo pipefail
          # Get latest linux_amd64 asset URL directly
          URL=$(curl -s https://api.github.com/repos/Checkmarx/ast-cli/releases/latest \
            | jq -r '.assets[] | select(.name | test("linux_amd64\\.tar\\.gz$")) .browser_download_url' | head -n1)

          # Fallback if URL not found
          if [ -z "$URL" ] || [ "$URL" = "null" ]; then
            VER="2.3.36"
            URL="https://github.com/Checkmarx/ast-cli/releases/download/${VER}/ast-cli_${VER}_linux_amd64.tar.gz"
          fi

          echo "Downloading: $URL"
          curl -L -o cx.tar.gz "$URL"
          tar -xzf cx.tar.gz || (echo "Failed to extract archive. Printing file info:" && file cx.tar.gz && exit 1)
          sudo mv cx /usr/local/bin/cx
          cx version
